### ISSUE TITLE
Status of File Layers

### ISSUE THREAD

**Issue by nalarsson** [julieshortridge/Climate-Analysis#4]
I went through and looked at all of the file layers for the models I have downloaded. There are a few missing files, but I'll go back and get those when I QA/QC the data I have downloaded. 

Long story short, **most of the models have 365 layers/days in their raster files**.

Because it's me and I've been having phenomenal luck recently, it turns out that only 4 of the 35 different models have a number of layers different than 365; when I randomly chose two models to analyze, the two I picked were in that group—statistically improbable! Just my luck... 

Anyway, we have 31 models that consistently have 365 days in their files. The good news is that the number of layers is consistent between the "nc_open" command in the "ncdf4" package and the "brick" command in the raster package. They are also consistent between parameters when I compared the "precipitation" files and the "max temperature" files. 

The Excel file below has the specific data. It's also in csv format if you prefer that.

[FileLayersByModel.xlsx](https://github.com/julieshortridge/Climate-Analysis/files/12082599/FileLayersByModel.xlsx)
[FileLayersByModel.csv.csv](https://github.com/julieshortridge/Climate-Analysis/files/12083161/FileLayersByModel.csv.csv)

**Comment by nalarsson** [comment]
Update: it's 5 out of 35, but that shouldn't change much

**Comment by julieshortridge** [comment]
Sounds good. Just don't use those models for now. We can address that down the road should we need to.

**Comment by nalarsson** [comment]
Models with issues (mostly for my reference):

UKESM1-0-LL
KACE-1-0-G
IITM-ESM
HadGEM3-GC31-MM
HadGEM3-GC31-LL
